import {
  attribute,
  autoGeneratedHashKey,
  rangeKey,
  table,
  // versionAttribute,
} from '@aws/dynamodb-data-mapper-annotations';

@table('customer')
export class Customer {
    @autoGeneratedHashKey()
    id: string;
    
    @rangeKey({defaultProvider: () => new Date()})
    createdAt: Date;

    @attribute()
    name: string;
    
    @attribute()
    sla: string;
}